layout_spectrum: 0.08017738512717187
typography_spectrum: 0.49820935912430286
color:
  brandStrength: 0.5583783520851284
  lightness: 0.45563072175718844
  saturation: 0.11638082889840007
  rhythmicContrast: 0.4348307275213301
  brandColors:
    - '#FFFFFF'
    - '#879DB2'
    - '#415C6F'
    - '#12242E'
    - '#AAC4DB'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e99ca6a-1fb5-4d08-b1a5-857f6cdeaf63.jpg
name: Evan Dorosheff
navigation:
  - url: 'https://soundcloud.com/dorosheff'
    name: Music
    type: external
  - url: 'https://www.facebook.com/evandorosheff/'
    name: Facebook
    type: external
title: DJ/Producer
