typography_spectrum: 0.4756239883136004
color:
  brandStrength: 0.5285640105139464
  lightness: 0.8728320351801813
  saturation: 0.05382613791152835
  rhythmicContrast: 0.5741442933212966
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.5956541323103011
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e99ca6a-1fb5-4d08-b1a5-857f6cdeaf63.jpg
name: Evan Dorosheff
navigation:
  - id: 'https://soundcloud.com/dorosheff'
    url: 'https://soundcloud.com/dorosheff'
    name: Music
    type: external
  - id: 'https://www.facebook.com/evandorosheff/'
    url: 'https://www.facebook.com/evandorosheff/'
    name: Facebook
    type: external
title: DJ/Producer
