typography_spectrum: 0.8510598647408187
color:
  brandStrength: 0.6654401076957583
  lightness: 0.04145031329244375
  saturation: 0.3980426243506372
  rhythmicContrast: 0.6865142856258899
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.2631579951848835
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e99ca6a-1fb5-4d08-b1a5-857f6cdeaf63.jpg
name: Evan Dorosheff
navigation:
  - id: 'https://soundcloud.com/dorosheff'
    url: 'https://soundcloud.com/dorosheff'
    name: Music
    type: external
  - id: 'https://www.facebook.com/evandorosheff/'
    url: 'https://www.facebook.com/evandorosheff/'
    name: Facebook
    type: external
title: DJ/Producer
